# -*- coding: utf-8 -*-
"""Modulo 2 - Daniele Veronesi

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jn1vb71eIYbU9xU_XtZO04ZfEobKUZ7b
"""

filmes = ['um sonho de liberdade', 'o poderoso chefao ii', 'batman e o cavaleiro das trevas', 'doze homens e uma sentença', 'a lista de schindler', 'o senhor dos aneis o retorno do rei', 'pulp fiction tempo de violencia', 'tres homens em conflito', 'o senhor dos aneis a sociedade do anel']
print(filmes)

filmes.insert(1,'o poderoso chefao')
print(filmes)

filmes.pop(0)
print(filmes)

filmes = {'pulp fiction tempo de violencia', 'tres homens em conflito', 'o senhor dos aneis a sociedade do anel'}
print(type(filmes))

filmes = ['pulp fiction tempo de violencia', 'tres homens em conflito', 'o senhor dos aneis a sociedade do anel']
print(type(filmes))

filmes = ['um sonho de liberdade','o poderoso chefao', 'o poderoso chefao ii', 'batman e o cavaleiro das trevas', 'doze homens e uma sentença', 'a lista de schindler', 'o senhor dos aneis o retorno do rei', 'pulp fiction tempo de violencia', 'tres homens em conflito', 'o senhor dos aneis a sociedade do anel']

filme = {'nome: um sonho de liberdade', 'ano: 1994', 'sinopse: dois homens presos se reunem ao longo de varios anos encontrando consolo e eventual redencao atraves de atos de decencia como'}
print(filme)

filme = {'nome: o poderoso chefao', 'ano: 1972', 'sinopse: o patriarca idoso de uma dinastia do crime organizado transfere o controle de seu império clandestino para seu filho relutante'}
print(filme)

filme = {'nome: o poderoso chefao ii', 'ano: 1974', 'sinopse: em 1950 michael corleone agora a frente da familia tenta expandir o negocio do crime a las vegas los angeles e cuba paralelamente e revelada a historia de vito corleone e de como saiu da sicilia e chegou a nova iorque'}
print(filme)

filme = {'nome: batman o cavaleiro das trevas', 'ano: 2008', 'sinopse: quando a ameaca conhecida como o coringa surge de seu passado causa estragos e caos nas pessoas de gotham o cavaleiro das trevas deve aceitar um dos maiores testes para combater a injustica'}
print(filme)

filme= {'nome: doze homens e uma sentenca', 'ano: 1957', 'sinopse: um jurado que se aposenta tenta evitar um erro judicial forcando seus colegas a reconsiderarem as evidencias'}
print(filme)

filme = {'nome: a lista de schindler', 'ano: 1993', 'sinopse: depois de testemunhar a perseguicao dos judaicos na polonia ocupada pelos alemaes durante a segunda guerra mundial o industrial oskar schindler se comeca a preocupar com sua forca de trabalho judaica'}
print(filme)

filme = {'nome: o senhor dos aneis o retorno do rei', 'ano: 2003', 'sinopse: gandalf e aragorn lideram o mundo dos homens contra o exercito de sauron para desviar o olhar de frodo e sam quando eles se aproximam a Montanha da perdicao com o um anel'}
print(filme)

filme = {'nome: pulp fiction tempo de violencia', 'ano: 1994', 'sinopse: as vidas de dois assassinos da mafia um boxeador um gangster e sua esposa e um par de bandidos se entrelacam em quatro historias de violencia e redencao'}
print(filme)

filme = {'nome: tres homens em conflito', 'ano: 1966', 'sinopse: um impostor se junta com dois homens para encontrar fortuna num remoto cemiterio'}
print(filme)

filme = {'nome: o senhor dos aneis a sociedade do anel', 'ano: 2001', 'sinopse: um manso hobbit do condado e oito companheiros partem em uma jornada para destruir o poderoso um anel e salvar a terra-média das trevas'}
print(filme)